---
adminusers:
  - name: label2
    first: Louis
    last: Abel
    password: ThisIsNotMyPassword1!
    title: Infrastructure IdM Manager
    loginshell: /bin/bash
  - name: gmk2
    first: Gregory
    last: Kurtzer
    password: ThisIsNotMyPassword1!
    title: Executive Director
    loginshell: /bin/bash
  - name: brian2
    first: Brian
    last: Clemens
    password: ThisIsNotMyPassword1!
    title: Project Manager
    loginshell: /bin/bash
  - name: hbjy2
    first: Hayden
    last: Young
    password: ThisIsNotMyPassword1!
    title: Web & Branding Manager
    loginshell: /bin/bash
  - name: jorp2
    first: Jordan
    last: Pisaniello
    password: ThisIsNotMyPassword1!
    title: Community Manager
    loginshell: /bin/bash
  - name: neil2
    first: Neil
    last: Hanlon
    password: ThisIsNotMyPassword1!
    title: Infrastructure Manager
    loginshell: /bin/bash
  - name: rlh2
    first: R. Leigh
    last: Hennig
    password: ThisIsNotMyPassword1!
    title: Operations Manager
    loginshell: /bin/bash
  - name: rfelsburg2
    first: Rob
    last: Felsburg
    password: ThisIsNotMyPassword1!
    title: Operations Manager
    loginshell: /bin/bash
  - name: tg2
    first: Taylor
    last: Goodwill
    password: ThisIsNotMyPassword1!
    title: Infrastructure Manager
    loginshell: /bin/bash
  - name: bagner2
    first: Benjamin
    last: Agner
    password: ThisIsNotMyPassword1!
    title: Security Director
    loginshell: /bin/bash
