export MIRROR="http://ftp.funet.fi/pub/linux/mirrors/centos/8/BaseOS/x86_64/kickstart/"
export KICKSTART_FILE="centos8/kickstart.cfg"
export OS_VARIANT="rhel8.2"
export EXTRA_ARGS=""
export DISK_SIZE="20"
