export MIRROR="https://mirror.phx1.us.spryservers.net/centos/8.3.2011/BaseOS/x86_64/kickstart/"
export KICKSTART_FILE="centos8/kickstart.cfg"
export OS_VARIANT="rhel8.2"
export EXTRA_ARGS=""
export DISK_SIZE="30"
