---
# This playbook is meant to be used with callable variables, like adhoc or AWX.
# What: Creates kerberos services in the idm infrastructure based on the variables provided

- name: Create Services
  hosts: ipaserver
  become: false
  gather_facts: false
  vars_files:
    - vars/encpass.yml

  tasks:
    - name: "Checking for user variables"
      assert:
        that:
          - ipaadmin_password | mandatory
          - ipaService | mandatory
        success_msg: "Required variables provided"
        fail_msg: "We are missing required information"

    - name: "Creating Kerberos Service"
      freeipa.ansible_freeipa.ipaservice:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ ipaService }}"
      tags:
        - services
