---
# Basic system configuration. All hardening should also be imported here.
# Use --extra-vars="host=..." and specify a hostname in the inventory or
# provide an ansible host group name. You can also just use "all" if you
# want to ensure all systems are up to date on the configuration.
- name: Configure system
  hosts: "{{ host }}"
  become: true

  # This is to try to avoid the handler issue in pre/post tasks
  handlers:
    - import_tasks: handlers/main.yml

  pre_tasks:
    - name: Check if ansible cannot be run here
      stat:
        path: /etc/no-ansible
      register: no_ansible

    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        success_msg: "We are able to run on this node"
        fail_msg: "/etc/no-ansible exists - skipping run on this node"

  tasks:
    - name: Loading Variables from OS Common
      import_tasks: tasks/variable_loader_common.yml

    - name: Configure SSH
      import_tasks: tasks/ssh_config.yml

    - name: Configure harden settings
      import_tasks: tasks/harden.yml

    - name: Configure PAM
      import_tasks: tasks/authentication.yml

    - name: Configure auditd
      import_tasks: tasks/auditd.yml

    - name: Configure grub
      import_tasks: tasks/grub.yml

    - name: Configure common scripts
      import_tasks: tasks/scripts.yml

  post_tasks:
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root
